In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
30   73    Male  Average        UG        No
1    68  Female     Poor        UG        No
3    72  Female     Good        PG        No
6    18    Male     Good    School        No
47   38  Female     Good        PG       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [7]:
train_x,test_x,train_y,test_y = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2)

In [8]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [9]:
oe.fit(train_x)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [10]:
X_train = oe.transform(train_x)

In [11]:
X_train

array([[0., 0.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.]])

In [12]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [13]:
X_train

array([[0., 0.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.]])

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
le.fit(train_y)

LabelEncoder()

In [17]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [18]:
y_train = le.transform(train_y)
y_test = le.transform(test_y)

In [19]:
y_train

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1])